# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # corne
  - board: nice_nano_v2
    shield: corne_central_dongle dongle_display
    artifact-name: corne_central_dongle
  - board: nice_nano_v2
    shield: corne_central_left
    artifact-name: corne_central_left
  - board: nice_nano_v2
    shield: corne_peripheral_left
    artifact-name: corne_peripheral_left
  - board: nice_nano_v2
    shield: corne_peripheral_right
    artifact-name: corne_peripheral_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: corne_central_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: corne_central_dongle_with_logging
